'use client';
import { useLocale } from './language';
import { useEffect, useRef, useState } from 'react';
import { dateLabel, routineTime } from '@/lib/dates';
import { type Product, type RoutineLog } from '@/lib/model';
import { snapshot } from '@/lib/routine-actions';
export function HistoryEditor({ record, products, busy, error, onClose, onSave }: { record: RoutineLog; products: Product[]; busy: boolean; error: string; onClose: () => void; onSave: (log: RoutineLog) => void }) {
 const {tr,locale}=useLocale();
 const [draft, setDraft] = useState(record);
 const [addId, setAddId] = useState('');
 const [validation, setValidation] = useState('');
 const dialog = useRef<HTMLDialogElement>(null);
 useEffect(() => { const previous = document.activeElement as HTMLElement; dialog.current?.showModal(); return () => previous?.focus(); }, []);
 const estimated = routineTime(record.date, record.timeOfDay);
 function timeFor(id: string) { const s = draft.steps.find(s => s.productId === id); const d = s?.completedAt ? new Date(s.completedAt) : estimated; return `${String(d.getHours()).padStart(2, '0')}:${String(d.getMinutes()).padStart(2, '0')}`; }
 return <dialog ref={dialog} className="editor" aria-labelledby="history-editor-title" onCancel={e => { e.preventDefault(); if (!busy) onClose(); }}><form onSubmit={e => { e.preventDefault(); if (draft.steps.some(s => s.completedAt && Date.parse(s.completedAt) > Date.now())) { setValidation('Usage times cannot be in the future.'); return; } onSave({ ...draft, decisions: draft.steps.map(s => ({ productId: s.productId, selected: !s.skipped, reason: 'Record corrected by you.' })) }); }}>
  <div className="editor-heading"><div><p className="eyebrow">{dateLabel(record.date,locale)} · {tr(record.timeOfDay==='morning'?'Morning':'Evening')}</p><h2 id="history-editor-title">{tr("What did you use?")}</h2></div><button className="icon-button" type="button" disabled={busy} onClick={onClose} aria-label={tr("Close history editor")}>×</button></div>
  <div className="editor-body"><p className="field-help">{tr("Record what happened, even if it differs from the suggestions. This does not recommend a treatment. Past uses default to ")}{record.timeOfDay === 'morning' ? '08:00' : '20:00'} {tr("local time; adjust the time below if needed.")}</p>{(error || validation) && <p role="alert" className="alert">{tr(validation || error)}</p>}
   {draft.steps.map(step => <div className="history-edit-row" key={step.productId}><strong>{products.find(p=>p.id===step.productId)?.brand ?? step.brand} {products.find(p=>p.id===step.productId)?.name ?? step.name}</strong><div className="form-grid"><label>{tr("Status")}<select value={step.completedAt ? 'used' : step.skipped ? 'skipped' : 'pending'} onChange={e => { const status = e.target.value; setDraft(r => ({ ...r, steps: r.steps.map(s => s.productId === step.productId ? { ...s, replacedById: undefined, skipped: status === 'skipped', completedAt: status === 'used' ? s.completedAt ?? estimated.toISOString() : null } : s) })); }}><option value="pending">{tr("Not recorded")}</option><option value="used">{tr("Used")}</option><option value="skipped">{tr("Skipped")}</option></select></label>{step.completedAt && <label>{tr("Time used")}<input required type="time" value={timeFor(step.productId)} onChange={e => { if (e.target.value) { const timestamp = new Date(`${record.date}T${e.target.value}:00`).toISOString(); setDraft(r => ({ ...r, steps: r.steps.map(s => s.productId === step.productId ? { ...s, completedAt: timestamp } : s) })); } }} /></label>}</div><button type="button" className="text-button danger" onClick={() => setDraft(r => ({ ...r, steps: r.steps.filter(s => s.productId !== step.productId).map(s => s.replacedById === step.productId ? { ...s, replacedById: undefined } : s) }))}>{tr("Remove from record")}</button></div>)}
   <label>{tr("Add a product to this record")}<select value={addId} onChange={e => setAddId(e.target.value)}><option value="">{tr("Choose a product")}</option>{products.filter(p => !draft.steps.some(s => s.productId === p.id)).map(p => <option value={p.id} key={p.id}>{p.brand} {p.name}{p.status !== 'active' ? tr(" ({0})", p.status) : ''}</option>)}</select></label><button type="button" className="text-button" disabled={!addId} onClick={() => { const p = products.find(p => p.id === addId); if (p) setDraft(r => ({ ...r, steps: [...r.steps, snapshot(p)].sort((a, b) => a.routineOrder - b.routineOrder) })); setAddId(''); }}>{tr("Add to record")}</button>
  </div><div className="editor-footer"><button type="button" className="text-button" disabled={busy} onClick={onClose}>{tr("Cancel")}</button><button className="primary" type="submit" disabled={busy}>{busy ? tr("Saving…") : tr("Save record")}</button></div>
 </form></dialog>;
}
