'use client';
import { useLocale } from './language';
import {useState} from 'react';
import {localDate,type Product,type RoutineLog,type Period} from '@/lib/model';
import {dateLabel,moveDate} from '@/lib/dates';
import {routineScore} from '@/lib/insights';
export default function Progress({products,routines,onRecord}:{products:Product[];routines:RoutineLog[];onRecord:(day:string,period:Period)=>void}) {
 const {tr,locale}=useLocale();
 const [end,setEnd]=useState(localDate());const result=routineScore(routines,end);
 const days=Array.from({length:7},(_,i)=>moveDate(end,-i));
 return <><div className="page-heading"><div><p className="eyebrow">{tr("YOUR ROUTINE OVER TIME")}</p><h1>{tr("History & progress.")}</h1><p className="muted">{tr("Your week at a glance. Open a morning or evening to record or correct it.")}</p></div></div><div className="score-window"><button className="icon-button" aria-label={tr("Previous week")} onClick={()=>setEnd(moveDate(end,-7))}>←</button><span>{dateLabel(result.start,locale)} — {dateLabel(end,locale)}</span><button className="text-button" onClick={()=>setEnd(localDate())}>{tr("This week")}</button><button className="icon-button" aria-label={tr("Next week")} disabled={end>=localDate()} onClick={()=>setEnd(moveDate(end,7)>localDate()?localDate():moveDate(end,7))}>→</button></div><section className="score-card"><span className="eyebrow">{tr("RECORDED ROUTINE FOLLOW-THROUGH")}</span><div className="score-number">{result.score===null?'—':tr("{0}%", result.score)}</div><p>{result.total?tr("{0} of {1} recorded steps marked used", result.used, result.total):tr("No completed-day records to score yet.")}</p><div className="score-counts"><span>{result.recordedDays}{tr("/7 days recorded")}</span><span>{result.skipped} {tr("skipped")}</span><span>{result.pending} {tr("unchecked")}</span></div><p className="field-help">{tr("Used ÷ (used + skipped + unchecked) in recorded routines. Missing days and today’s unfinished routines are not scored. Swapped-out steps are excluded. Skipping can be the right choice; this is not a skin-health score.")}</p></section><div className="journal-list">{days.map(day=><section className="journal-day" key={day}><h2>{dateLabel(day,locale)}</h2><div className="journal-periods">{(['morning','evening'] as const).map(period=>{const log=routines.find(r=>r.date===day && r.timeOfDay===period);const used=log?.steps.filter(s=>s.completedAt && !s.skipped) ?? [];return <button className="history-card" key={period} onClick={()=>onRecord(day,period)}><strong>{period==='morning'?tr("Morning"):tr("Evening")}</strong><span>{log ? tr("{0} products used", used.length):tr("Not recorded")}</span><span>{used.map(s=>products.find(p=>p.id===s.productId)?.name ?? s.name).join(' · ')}</span><span className="history-link">{log?tr("View or correct →"):tr("Record this routine →")}</span></button>;})}</div></section>)}</div></>;
}
