'use client';
import { useLocale } from './language';
import { useState } from 'react';
import {Droplets,Sun,Sparkles} from 'lucide-react';
import { type Product, rolesFor } from '@/lib/model';
import { coverageFor, recommendationsFor } from '@/lib/recommendations';
import { benefitFor, reviewedOn, sources } from '@/lib/product-guidance';
export default function Recommendations({ products, onEdit, onGentle, busy }: { products: Product[]; onEdit: (p: Product) => void; onGentle: () => void; busy: boolean }) {
 const {tr}=useLocale();
 const [goal, setGoal] = useState('comfort');
 const coverage = coverageFor(products); const advice = recommendationsFor(products);
 const active = products.filter(p=>p.status === 'active');
 const goalRoles = goal === 'comfort' ? ['soothing','hydrating','moisturizer'] : goal === 'tone' ? ['brightening','sunscreen'] : ['pore_exfoliating','pore_mask'];
 const matches = active.filter(p=>rolesFor(p).some(r=>goalRoles.includes(r)));
 return <><div className="page-heading"><div><p className="eyebrow">{tr("MAKE EACH STEP COUNT")}</p><h1>{tr("Your routine, considered.")}</h1><p className="muted">{tr("What you already cover, where products overlap, and what is worth changing.")}</p></div></div>
 <section className="advice-overview"><h2>{coverage.every(s=>s.products.length) ? tr("Your basic steps are covered in your settings.") : tr("Start with the gaps in your basic steps.")}</h2><p>{coverage.every(s=>s.products.length) ? tr("You do not need more steps just to make your routine complete. Review the options below before adding a product.") : tr("Check your existing products and their schedules before buying something new.")}</p><div className="coverage-grid">{coverage.map(slot=><div key={slot.key}><strong>{tr(slot.title)}</strong><span>{slot.products.length ? tr("{0} configured", slot.products.length) : tr("Not configured")}</span></div>)}</div><p className="field-help">{tr("Coverage means active and enabled for that time of day. It does not verify daily use, label protection, tolerability or availability under spacing limits.")}</p></section>
 <section className="progress-section"><h2>{tr("Focus on a benefit")}</h2><div className="navigation benefit-navigation" role="group" aria-label={tr("What matters for this review?")}>{[{id:'comfort',label:'Hydration & comfort',Icon:Droplets},{id:'tone',label:'Uneven-looking tone',Icon:Sun},{id:'pores',label:'Surface oil & texture',Icon:Sparkles}].map(({id,label,Icon})=><button type="button" key={id} aria-pressed={goal===id} onClick={()=>setGoal(id)}><Icon size={18}/>{tr(label)}</button>)}</div><p className="field-help">{tr("This changes the comparison below, not your schedule. ")}{goal === 'pores' ? tr("Exfoliation and masks are optional. If skin feels dry or irritated, prioritize comfort rather than extra exfoliation.") : tr("Start with products you already tolerate. Make one change at a time.")}</p><div className="benefit-list">{matches.length ? matches.map(p=><button key={p.id} onClick={()=>onEdit(p)}><strong>{p.name}</strong><span>{tr(benefitFor(p))}</span><small>{tr("Benefits & how to use →")}</small></button>) : <p>{tr("No active product has this role assigned. This alone does not mean you need to buy one.")}</p>}</div></section>
 <section className="progress-section"><h2>{tr("Priorities for your cabinet")}</h2><p className="field-help">{tr("These are practical suggestions based on your products and settings. They cannot assess your skin or replace a prescribed treatment plan.")}</p>{advice.map((item,i)=><article className="advice-card" key={item.id}><span className="eyebrow">{String(i+1).padStart(2,'0')} {tr("· ROUTINE REVIEW")}</span><h3>{tr(item.title)}</h3><p>{tr(item.why)}</p><p className="advice-action">{tr(item.action)}</p><div className="advice-links">{item.productIds.map(id=>products.find(p=>p.id===id)).filter((p): p is Product=>!!p).map(p=><button className="text-button" key={p.id} onClick={()=>onEdit(p)}>{p.name} →</button>)}</div>{item.id==='intensity' && <button className="primary" disabled={busy} onClick={onGentle}>{tr("Use gentle suggestions")}</button>}<a href={item.source} target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer">{tr("Why this matters · AAD guidance ↗")}</a></article>)}</section>
 <section className="progress-section"><h2>{tr("Alternatives worth considering")}</h2><p>{tr("You already have the main steps when their schedules are enabled. These are optional alternatives, not products you need to add.")}</p><article className="advice-card"><h3>{tr("SKIN1004 · Madagascar Centella Quick Calming Pad")}</h3><p>{tr("If you want pads for hydration rather than exfoliation, this centella, panthenol and hyaluronic-acid pad has a different purpose from Zero Pore Pad. Use it instead of an active pad, not as an extra layer. Your Centella ampoule already covers similar soothing care.")}</p><a href="https://www.skin1004.com/products/skin1004-madagascar-centella-quick-calming-pad" target="_blank" rel="noopener noreferrer">{tr("Manufacturer details ↗")}</a></article><article className="advice-card"><h3>{tr("SKIN1004 · Madagascar Centella Soothing Cream")}</h3><p>{tr("A possible gel-cream alternative if your current moisturizers do not suit your preferred texture. The brand lists centella, ceramide NP and cholesterol for moisturizing care. Compare ingredients and patch test; this is not a reason to replace a cream that works for you.")}</p><a href="https://www.skin1004.com/products/skin1004-madagascar-centella-soothing-cream" target="_blank" rel="noopener noreferrer">{tr("Manufacturer details ↗")}</a></article></section>
 <section className="progress-section"><h2>{tr("Keep sun protection practical")}</h2><p>{tr("Choose one sunscreen with broad-spectrum SPF 30 or higher. Check its label for reapplication and water resistance; a morning checkmark does not track protection throughout the day.")}</p><a className="source-card" href={sources.sun} target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer">{tr("AAD · selecting everyday skincare ↗")}</a><p className="field-help">{tr("Product information reviewed ")}{tr(reviewedOn)}{tr(". Advice is generated locally from your cabinet using reviewed guidance, not live trends or a skin diagnosis. Sources open online only when selected. Your cabinet is not uploaded.")}</p></section></>;
}
