'use client';
import { translator } from '@/lib/i18n';
import { useLocale, LanguageProvider } from './language';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { Sun, Moon, Plus, Check, ArrowLeft, ArrowRight, Droplets, Leaf, Pencil, Pause, Play, Trash2, X, Settings, History, ShoppingBag } from 'lucide-react';
import { categories, currentPeriod, localDate, defaultSettings, rolesFor, schedulingFor, stageFor, stageLabels, functionalRoles, orderFor, type RoutineSettings, type RoutineStage, type Product, type Period, type RoutineLog } from '@/lib/model';
import Progress from './progress';
import Recommendations from './recommendations';
import { benefitFor } from '@/lib/product-guidance';
import { previewRoutine } from '@/lib/insights';
import SettingsPage from './settings';
import Rebuy from './rebuy';
import WeekOverview from './week-overview';
import ProductDetails from './product-details';
import { HistoryEditor } from './history';
import SwapDialog from './swap-dialog';
import { clearRebuyReminder, routineTime, moveDate, lifecycle, dateLabel } from '@/lib/dates';
import { swapChoices } from '@/lib/routine-actions';
import { appPath } from '@/lib/paths';
import { initializeCabinet, recalculateRoutine, setFavorite, saveSettings, readData, saveProduct, deleteProduct, completeStep, changeRoutine, saveHistory } from '@/lib/database';

const blank = (): Product => ({ id: crypto.randomUUID(), brand: '', name: '', category: 'Cleanser', timeOfDay: 'both', routineOrder: 10, autoOrder: true, status: 'active', instruction: '', notes: '', openedDate: '', paoMonths: null, expirationDate: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() });
type Data = { products: Product[]; routines: RoutineLog[]; settings: RoutineSettings; canUndoRestore?: boolean };
export default function SkinApp() {
  const [data, setData] = useState<Data>({ products: [], routines: [], settings: defaultSettings });
  const tr=translator(data.settings.language ?? 'en');
  const locale=data.settings.language === 'fr'?'fr-FR':'en-US';
  const [ready, setReady] = useState(false);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [view, setView] = useState<'today' | 'products' | 'history' | 'settings' | 'advice' | 'rebuy'>('today');
  const [period, setPeriod] = useState<Period>('morning');
  const [date, setDate] = useState('');
  const [today, setToday] = useState(localDate());
  const [historyDraft, setHistoryDraft] = useState<{ record: RoutineLog; expected: string | null } | null>(null);
  const [swapId, setSwapId] = useState<string | null>(null);
  const manualDate = useRef(false);
  const [editor, setEditor] = useState<Product | null>(null);
  const [filter, setFilter] = useState<'all' | Product['category']>('all');
  const [detailId,setDetailId] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const lock = useRef(false);
  const manualPeriod = useRef(false);
  const [manualTime, setManualTime] = useState(false);
  const [clockPeriod, setClockPeriod] = useState<Period>('morning');
  const clockWindow = useRef('');
  const opener = useRef<HTMLElement | null>(null);
  async function refresh() { setData(await readData()); setReady(true); }
  useEffect(() => {
    const clock = () => {
      const now = new Date(); const day = localDate(now); const time = currentPeriod(now); const window = `${day}:${time}`;
      if (window !== clockWindow.current) { manualPeriod.current = false; setManualTime(false); clockWindow.current = window; }
      setClockPeriod(time); setToday(day); if (!manualDate.current) setDate(day); if (!manualPeriod.current) setPeriod(time);
    };
    clock();
    const load = () => { if (document.visibilityState === 'visible') { clock(); void refresh().catch(() => setError('Your saved data could not be opened. Please reload to try again.')); } };
    void initializeCabinet().then(refresh).catch(() => setError('Local storage is unavailable. Check your browser settings, then reload.'));
    const timer = setInterval(clock, 30000);
    document.addEventListener('visibilitychange', load);
    const channel = typeof BroadcastChannel !== 'undefined' ? new BroadcastChannel('skin-ritual-updates') : null;
    if (channel) channel.onmessage = load;
    if (process.env.NODE_ENV === 'production' && 'serviceWorker' in navigator) {
      void navigator.serviceWorker.register(appPath('sw.js'), { scope: appPath(''), updateViaCache: 'none' }).then(registration => registration.update()).catch(() => setNotice('Offline setup was unavailable. You can still use the app online.'));
    }
    return () => { clearInterval(timer); document.removeEventListener('visibilitychange', load); channel?.close(); };
  }, []);
  async function mutate(action: () => Promise<void>, message = '') {
    if (lock.current) return false;
    lock.current = true; setBusy(true); setError(''); setNotice('');
    try {
      await action(); await refresh(); setNotice(message);
      if (typeof BroadcastChannel !== 'undefined') { const channel = new BroadcastChannel('skin-ritual-updates'); channel.postMessage('changed'); channel.close(); }
      return true;
    } catch (e) { setError(e instanceof Error ? e.message : 'That change could not be saved. Please try again.'); return false; }
    finally { lock.current = false; setBusy(false); }
  }
  function edit(product?: Product) { opener.current = document.activeElement as HTMLElement; setEditor(product ?? blank()); }
  function closeEditor() { setEditor(null); requestAnimationFrame(() => opener.current?.focus()); }
  const log = data.routines.find(r => r.id === `${date}:${period}`);
  const evaluationTime = routineTime(date || today, period);
  const future = date > today;
  const plan = previewRoutine(data.products, period, data.routines, date || today, data.settings);
  const draftRecord: RoutineLog = log ?? { id: `${date}:${period}`, date, timeOfDay: period, ...plan, completedAt: null, updatedAt: new Date().toISOString() };
  function navigate(day: string, time?: Period) { manualDate.current = true; setDate(day); if (time) { manualPeriod.current = true; setManualTime(true); setPeriod(time); } setView('today'); setNotice(''); }
  function recordAt(day: string,time: Period) { const record=data.routines.find(r=>r.id===`${day}:${time}`);setError('');setHistoryDraft({record:record ?? {id:`${day}:${time}`,date:day,timeOfDay:time,steps:[],completedAt:null,updatedAt:new Date().toISOString()},expected:record?.updatedAt ?? null}); }
  function tag(p:Product){void mutate(()=>saveProduct({...p,almostEmpty:!p.almostEmpty,updatedAt:new Date().toISOString()}));}
  const lifecycleAlerts = data.products.filter(p => p.status !== 'finished').map(p => ({ product: p, life: lifecycle(p, today, locale) })).filter(item => item.life && item.life.days <= 30).sort((a,b) => a.life!.date.localeCompare(b.life!.date));
  const steps = (log?.steps ?? plan.steps).filter(step=>!step.replacedById && !log?.decisions?.some(d=>d.productId===step.productId && d.reason==='Swapped out by you; not counted as use.')).map(step=>{ const current=data.products.find(p=>p.id===step.productId); return current ? {...step,name:current.name,brand:current.brand} : step; });
  const undoSwaps = log?.undoActions?.filter(action => {
    const ids = new Set([...action.before, ...action.after].map(s => s.productId));
    return action.kind === 'swap' && JSON.stringify(log.steps.filter(s => ids.has(s.productId))) === JSON.stringify(action.after);
  }) ?? [];
  const canRecalculate = !!log && !future && !log.steps.some(s=>s.completedAt);
  const completed = steps.filter(s => s.completedAt).length;
  const skipped = steps.filter(s => s.skipped).length;
  const handled = completed + skipped;
  const done = steps.length > 0 && handled === steps.length;
  const active = data.products.filter(p => p.status === 'active').length;
  const shownProducts = data.products.filter(p => filter === 'all' || p.category === filter).sort((a, b) => orderFor(a) - orderFor(b) || a.name.localeCompare(b.name));
  const detailProduct=data.products.find(p=>p.id===detailId);
  return <LanguageProvider language={data.settings.language ?? 'en'}><div className="app-shell">
    <header className="topbar"><a className="brand" href={appPath('')} aria-label={tr("Skin Ritual home")}><span className="brand-mark"><Droplets size={21} /></span>{tr("skin ritual")}<span className="brand-period">.</span></a><button className="settings-button" onClick={() => setView('settings')} aria-label={tr("Settings")}><Settings size={18} /><span>{tr("Settings")}</span></button></header>
    <nav className="navigation" aria-label={tr("Main navigation")}><button onClick={() => { setView('today'); setDate(today); setPeriod(currentPeriod()); manualDate.current = false; manualPeriod.current = false; setManualTime(false); }} aria-current={view === 'today' ? 'page' : undefined}><Sun size={18} /> {tr("Today")}</button><button onClick={() => setView('products')} aria-current={view === 'products' ? 'page' : undefined}><Droplets size={18} /> {tr("Products")}</button><button onClick={() => setView('advice')} aria-current={view === 'advice' ? 'page' : undefined}><Leaf size={18} /> {tr("Advice")}</button><button onClick={() => setView('history')} aria-current={view === 'history' ? 'page' : undefined}><History size={18} /> {tr("History")}</button><button onClick={() => setView('rebuy')} aria-current={view === 'rebuy' ? 'page' : undefined}><ShoppingBag size={18} /> {tr("Rebuy")}</button></nav>
    <main>
      {error && <div className="alert" role="alert">{tr(error)}{!ready && <button className="text-button" onClick={() => location.reload()}>{tr("Reload")}</button>}</div>}
      {notice && <p className="notice" role="status">{tr(notice)}</p>}
      {!ready ? <div className="empty loading" role="status">{error ? tr("Your data has not been loaded.") : tr("Opening your cabinet…")}</div> : view === 'today' ? <>
        <div className="page-heading"><div><p className="eyebrow">{date && new Date(`${date}T12:00:00`).toLocaleDateString(locale, { weekday: 'long', month: 'long', day: 'numeric' })}</p><h1>{tr("A little time for you.")}</h1><p className="muted">{tr("Your routine, one step at a time.")}</p></div><span className="heading-icon">{period === 'morning' ? <Sun size={32} strokeWidth={1.3} /> : <Moon size={32} strokeWidth={1.3} />}</span></div>
        <div className="week-navigation" aria-label={tr("Browse routine days")}><div className="week-heading"><button className="icon-button" aria-label={tr("Previous week")} onClick={() => navigate(moveDate(date, -7))}><ArrowLeft size={17} /></button><span>{new Date(`${date}T12:00:00`).toLocaleDateString(locale, { month: 'long', year: 'numeric' })}</span><button className="text-button" onClick={() => { manualDate.current = false; manualPeriod.current = false; setManualTime(false); setDate(today); setPeriod(currentPeriod()); }}>{tr("Today")}</button><button className="icon-button" aria-label={tr("Next week")} onClick={() => navigate(moveDate(date, 7))}><ArrowRight size={17} /></button></div><div className="day-strip">{Array.from({ length: 7 }, (_, i) => moveDate(date, i - 3)).map(day => <button key={day} className={day === today ? 'is-today' : ''} aria-pressed={day === date} aria-label={dateLabel(day,locale)} onClick={() => navigate(day)}><span>{new Date(`${day}T12:00:00`).toLocaleDateString(locale, { weekday: 'short' })}</span><strong>{new Date(`${day}T12:00:00`).getDate()}</strong></button>)}</div></div>
        {future ? <p className="date-context" role="status">{plan.projected ? tr("Projected routine · assumes you use the suggested steps between now and this day. Nothing is recorded. Your actual logs can change these choices.") : tr("Tentative future routine · based only on current records. Checkmarks are disabled.")}</p> : date < today ? <div className="date-context"><p>{tr("Past day · open History to record or correct this routine.")}</p><button className="text-button" onClick={()=>recordAt(date,period)}>{tr("Edit record")}</button></div> : null}
        <div className="today-layout"><div className="routine-column"><section className="routine-panel" aria-label={tr("Today's routine")}>
          <div className="period-switch" aria-label={tr("Routine time")}>{(clockPeriod === 'morning' ? ['morning', 'evening'] as const : ['evening', 'morning'] as const).map(t => <button key={t} aria-pressed={period === t} onClick={() => { manualPeriod.current = true; setManualTime(true); setPeriod(t); setNotice(''); }}>{t === 'morning' ? <Sun size={17} /> : <Moon size={17} />} {t === 'morning' ? tr("Morning") : tr("Evening")}</button>)}</div>
          <p className="period-mode">{manualTime ? <>{tr("Manual selection until the next morning/evening change. ")}<button className="text-button" onClick={() => { manualPeriod.current = false; setManualTime(false); setPeriod(currentPeriod()); }}>{tr("Use current time")}</button></> : tr("Following your local time · morning 5am–5pm, evening 5pm–5am.")}</p><div className="routine-title"><h2>{period === 'morning' ? tr("Start fresh") : tr("Wind down")}</h2><span>{steps.length} {steps.length === 1 ? tr("step") : tr("steps")}</span></div>
          {steps.length > 0 ? <>
            <div className="progress-label"><span>{done ? tr("All done for now") : tr("{0} used · {1} skipped", completed, skipped)}</span><span>{Math.round(handled / steps.length * 100)}%</span></div><div className="progress-track" role="progressbar" aria-label={tr("Routine completion")} aria-valuenow={handled} aria-valuemin={0} aria-valuemax={steps.length}><div style={{ width: `${handled / steps.length * 100}%` }} /></div>
            <ol className="steps">{steps.map((step, i) => <li key={step.productId} className={`step ${step.completedAt ? 'checked' : ''} ${step.skipped ? 'skipped' : ''}`}><span className="step-number">{String(i + 1).padStart(2, '0')}</span><div className="step-main"><label className="step-content"><span className="step-category">{tr(step.category)}</span><span className="step-name">{step.name}</span>{step.brand && <span className="step-brand">{step.brand}</span>}{step.instruction && <span className="step-instruction">{step.instruction}</span>}<input className="step-checkbox" type="checkbox" checked={!!step.completedAt} disabled={busy || future || step.skipped} aria-label={tr("Mark {0} complete", step.name)} onChange={e => void mutate(() => completeStep(date, period, step.productId, e.target.checked))} /><span className="checkbox-visual" aria-hidden="true">{step.completedAt && <Check size={18} />}</span></label><div className="step-tools">{step.skipped ? <span>{tr("Skipped · not counted as use")}</span> : !step.completedAt && !future ? <><button disabled={busy} onClick={() => void mutate(() => changeRoutine(date, period, step.productId, 'skip'))}>{tr("Skip")}</button><button disabled={busy} onClick={() => { setError(''); setSwapId(step.productId); }}>{tr("Swap")}</button></> : null}{step.skipped && !step.replacedById && !future && <button disabled={busy} onClick={() => void mutate(() => changeRoutine(date, period, step.productId, 'pending'))}>{tr("Undo skip")}</button>}{!future && undoSwaps.filter(action=>action.after.find(s=>!s.skipped)?.productId===step.productId).map(action=><button key={action.id} disabled={busy} onClick={()=>void mutate(()=>changeRoutine(date,period,action.id,'undo'))}>{tr("Undo swap")}</button>)}{data.products.filter(p=>p.id===step.productId).map(p=><button type="button" className="today-stock" key={p.id} aria-pressed={!!p.almostEmpty} disabled={busy} onClick={()=>tag(p)}>{p.almostEmpty ? tr("Almost empty · undo") : tr("Almost empty")}</button>)}</div></div></li>)}</ol>
            <div className={`routine-footer ${done ? 'complete' : ''}`} role="status">{done ? <><Check size={18} /> {tr("Routine complete · ")}{completed} {tr("used")}{skipped > 0 ? tr(", {0} skipped", skipped) : ''}.</> : future ? tr("Preview only · return on this day to record usage.") : tr("Check off each product as you use it.")}</div>
          </> : <div className="empty"><span className="empty-icon"><Droplets size={30} strokeWidth={1.3} /></span><h3>{data.products.length ? tr("Make room for your {0}.", tr(period)) : tr("Your routine starts here.")}</h3><p>{data.products.length ? tr("Check product schedules and routine preferences. Assign an active product to {0} or both to see it here.", period) : tr("Add the products you already use. We’ll put them in your order.")}</p><button className="primary" onClick={() => data.products.length ? setView('products') : edit()}>{data.products.length ? tr("Open your cabinet") : tr("Add your first product")}<Plus size={17} /></button></div>}
            {canRecalculate && <div className="recalculate"><button className="text-button" disabled={busy} onClick={()=>void mutate(()=>recalculateRoutine(date,period,log!.updatedAt),'Routine recalculated.')}>{tr("Recalculate this routine")}</button><p className="field-help">{tr("Applies current preferences and resets skips and swaps. Available before any product is marked used.")}</p></div>}
          <details className="decision-details"><summary>{tr("Why these products?")}</summary><p className="field-help">{tr("What each product contributes. Product benefits summarize manufacturer information; your own label takes priority.")}</p>{steps.filter(step => !step.skipped).map(step => { const product = data.products.find(p => p.id === step.productId); return <div key={step.productId} className="decision-row"><strong>{step.name}</strong><span>{product ? tr(benefitFor(product)) : tr("This saved product no longer matches your cabinet. Its benefits cannot be verified from the saved name alone.")}</span>{product && <button className="text-button" onClick={() => setDetailId(product.id)}>{tr("Benefits & how to use →")}</button>}</div>; })}</details>
        </section><WeekOverview products={data.products} routines={data.routines} settings={data.settings} start={date || today} onSelect={navigate}/></div><aside className="aside">{lifecycleAlerts.length > 0 && <section className="lifecycle-alerts"><h3>{tr("Dates to keep an eye on")}</h3>{lifecycleAlerts.map(({ product, life }) => <button key={product.id} onClick={() => edit(product)}><strong>{product.name}</strong><span>{tr(life!.message)}</span></button>)}<p className="field-help">{tr("Based on your recorded dates, not an assessment of product condition.")}</p></section>}<div className="aside-card"><span className="eyebrow">{tr("YOUR CABINET")}</span><h3>{active === 1 ? tr("{0} active product",active) : tr("{0} active products",active)}</h3><p>{tr("Add what you use. Pause what you’re taking a break from.")}</p><button className="text-button" onClick={() => setView('products')}>{tr("Manage products ")}<ArrowRight size={16} /></button></div><div className="quiet-note"><Leaf size={21} strokeWidth={1.4} /><p>{tr("A simple ritual.")}<br />{tr("At your own pace.")}</p></div></aside></div>
      </> : view === 'settings' ? <SettingsPage settings={data.settings} busy={busy} canUndo={!!data.canUndoRestore} mutate={mutate} onSave={settings=>void mutate(()=>saveSettings(settings))}/> : view === 'rebuy' ? <Rebuy products={data.products} today={today} onClear={p=>void mutate(()=>saveProduct(clearRebuyReminder(p,today)))} onDetails={p=>setDetailId(p.id)} busy={busy}/> : view === 'advice' ? <Recommendations products={data.products} onEdit={p=>setDetailId(p.id)} busy={busy} onGentle={() => void mutate(() => saveSettings({ ...data.settings, intensity: 'gentle' }), 'Gentle suggestions enabled. Started routines keep their saved steps.')} /> : view === 'history' ? <Progress products={data.products} routines={data.routines} onRecord={recordAt}/> : <>
        <div className="page-heading cabinet-heading"><div><p className="eyebrow">{tr("WHAT YOU REACH FOR")}</p><h1>{tr("Your cabinet.")}</h1><p className="muted">{tr("Only the products that belong in your routine.")}</p></div><button className="primary" onClick={() => edit()}><Plus size={18} /> {tr("Add product")}</button></div>
        <div className="cabinet-toolbar"><div className="category-menu choice-menu" role="group" aria-label={tr("Product type")}><button type="button" aria-pressed={filter==='all'} onClick={()=>setFilter('all')}>{tr("All product types")}</button>{categories.filter(c=>data.products.some(p=>p.category===c)).map(c=><button type="button" key={c} aria-pressed={filter===c} onClick={()=>setFilter(c)}>{tr(c)}</button>)}</div></div>
        {shownProducts.length === 0 ? <div className="empty cabinet-empty"><Droplets size={32} strokeWidth={1.2} /><h3>{data.products.length ? tr("No {0} products yet.", filter === 'all' ? '' : tr(filter)) : tr("A home for your everyday essentials.")}</h3><p>{data.products.length ? tr("Products in this category will appear here.") : tr("Start with one product. You can build the rest as you go.")}</p><button className="primary" onClick={() => edit()}><Plus size={17} /> {tr("Add a product")}</button></div> : <div className="product-list">{shownProducts.map(p => <article className="product-row" key={p.id}><div className="product-order" title={tr(stageLabels[stageFor(p)])}><Droplets size={16} /></div><div className="product-info"><p className="step-category">{tr(p.category)}</p><h3>{p.name}</h3><button className="text-button favorite-button" aria-pressed={!!p.favorite} disabled={busy} onClick={()=>void mutate(()=>setFavorite(p.id))}>{p.favorite ? tr("★ Favorite · rotate instead") : tr("☆ Prefer this product")}</button>{p.brand && <p className="muted">{p.brand}</p>}<p className="product-benefit">{tr(benefitFor(p))}</p><button className="text-button" onClick={() => setDetailId(p.id)}>{tr("Benefits & how to use →")}</button>{lifecycle(p, today, locale) && <p className={`lifecycle-label ${lifecycle(p, today, locale)!.days <= 30 ? 'due' : ''}`}>{tr(lifecycle(p, today, locale)!.message)}</p>}<div className="product-meta">{p.seeded && <span className="status-tag">{tr("Editable default")}</span>}{!schedulingFor(p).enabled && <span className="status-tag">{tr("Schedule off")}</span>}<span>{p.timeOfDay === 'both' ? tr("Morning & evening") : p.timeOfDay === 'morning' ? tr("Morning") : tr("Evening")}</span>{p.status !== 'active' && <span className="status-tag">{tr(p.status)}</span>}</div></div><button className="stock-tag" aria-pressed={!!p.almostEmpty} disabled={busy} onClick={()=>tag(p)}>{p.almostEmpty ? tr("Almost empty · undo") : tr("Almost empty")}</button><div className="product-actions"><button className="icon-button" title={tr("Edit {0}", p.name)} aria-label={tr("Edit {0}", p.name)} onClick={() => edit(p)}><Pencil size={17} /></button><button className="icon-button" disabled={busy} title={p.status === 'active' ? tr("Pause product") : tr("Activate product")} aria-label={tr("{0} {1}", p.status === 'active' ? 'Pause' : 'Activate', p.name)} onClick={() => void mutate(() => saveProduct({ ...p, status: p.status === 'active' ? 'paused' : 'active', updatedAt: new Date().toISOString() }), p.status === 'active' ? 'Product paused.' : 'Product activated.')}>{p.status === 'active' ? <Pause size={17} /> : <Play size={17} />}</button></div></article>)}</div>}
        <p className="cabinet-help">{tr("Steps follow product roles. “Both” means eligible morning and evening; rotation chooses a subset. All starter classifications and limits are editable defaults.")}</p>
      </>}

    </main><footer className="site-footer"><span>{tr("skin ritual.")}</span><span>{tr("A moment of care, every day.")}</span></footer>
    {detailProduct && <ProductDetails product={detailProduct} busy={busy} onClose={()=>setDetailId(null)} onTag={()=>tag(detailProduct)} onEdit={()=>{setDetailId(null);edit(detailProduct);}}/>}
    {historyDraft && <HistoryEditor record={historyDraft.record} products={data.products} busy={busy} error={error} onClose={() => setHistoryDraft(null)} onSave={record => void mutate(() => saveHistory(record, historyDraft.expected), 'Usage record saved.').then(ok => { if (ok) setHistoryDraft(null); })} />}
    {swapId && <SwapDialog name={steps.find(s => s.productId === swapId)?.name ?? 'product'} candidates={swapChoices(draftRecord, swapId, data.products, data.routines, evaluationTime, data.settings)} busy={busy} error={error} onClose={() => setSwapId(null)} onSelect={replacement => void mutate(() => changeRoutine(date, period, swapId, 'swap', replacement), 'Step swapped.').then(ok => { if (ok) setSwapId(null); })} />}
    {editor && <ProductEditor products={data.products} product={editor} existing={data.products.some(p => p.id === editor.id)} busy={busy} error={error} onClose={closeEditor} onSave={async p => { if (await mutate(() => saveProduct(p), 'Product saved.')) closeEditor(); }} onDelete={async () => { if (await mutate(() => deleteProduct(editor.id), 'Product deleted. Existing routine records are kept.')) closeEditor(); }} />}
  </div></LanguageProvider>;
}
function ProductEditor({ products, product, existing, busy, error, onClose, onSave, onDelete }: { products: Product[]; product: Product; existing: boolean; busy: boolean; error: string; onClose: () => void; onSave: (p: Product) => Promise<void>; onDelete: () => Promise<void> }) {
 const {tr,locale}=useLocale();
  const [draft, setDraft] = useState(product);
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [validation, setValidation] = useState('');
  const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => { dialog.current?.showModal(); }, []);
  function field<K extends keyof Product>(key: K, value: Product[K]) { setDraft(p => ({ ...p, [key]: value })); }
  function submit(e: FormEvent) { e.preventDefault(); if (!draft.name.trim()) { setValidation('Enter a product name.'); return; } setValidation(''); void onSave({ ...draft, name: draft.name.trim(), brand: draft.brand.trim(), updatedAt: new Date().toISOString() }); }
  return <dialog ref={dialog} className="editor" aria-labelledby="editor-title" onCancel={e => { e.preventDefault(); if (!busy) onClose(); }}><form onSubmit={submit}>
    <div className="editor-heading"><div><p className="eyebrow">{tr("YOUR CABINET")}</p><h2 id="editor-title">{existing ? tr("Edit product") : tr("Add a product")}</h2></div><button type="button" className="icon-button" disabled={busy} onClick={onClose} aria-label={tr("Close product editor")}><X size={21} /></button></div>
    <div className="editor-body">{(validation || error) && <p role="alert" className="alert">{tr(validation || error)}</p>}
      <label>{tr("Product name ")}<span className="required">*</span><input autoFocus={!existing} required maxLength={160} value={draft.name} onChange={e => field('name', e.target.value)} placeholder={tr("e.g. Madagascar Centella Ampoule")} /></label>
      <label>{tr("Brand")}<input maxLength={100} value={draft.brand} onChange={e => field('brand', e.target.value)} placeholder={tr("e.g. Skin1004")} /></label>
      <div className="form-grid"><label>{tr("Category")}<select value={draft.category} onChange={e => setDraft(p => ({ ...p, category: e.target.value as Product['category'], roles: undefined, stepOverride: null, autoOrder: true }))}>{categories.map(c => <option key={c} value={c}>{tr(c)}</option>)}</select></label><label>{tr("Routine step")}<select value={draft.stepOverride ?? ''} onChange={e => setDraft(p => ({ ...p, autoOrder: true, stepOverride: (e.target.value || null) as RoutineStage | null }))}><option value="">{tr("Automatic · ")}{tr(stageLabels[stageFor({ ...draft, stepOverride: null })])}</option>{Object.entries(stageLabels).map(([key, label]) => <option key={key} value={key}>{tr(label)}</option>)}</select></label></div>
      <fieldset><legend>{tr("When do you use it?")}</legend><div className="assignment">{(['morning', 'evening', 'both'] as const).map(t => <label key={t}><input type="radio" name="time" value={t} checked={draft.timeOfDay === t} onChange={() => field('timeOfDay', t)} /><span>{t === 'both' ? tr("Both") : t === 'morning' ? tr("Morning") : tr("Evening")}</span></label>)}</div></fieldset>
      {draft.seeded && <p className="default-note">{tr("Starter product · all classifications and scheduling values below are editable defaults. Opening and expiration dates are yours to record.")}</p>}
      <section className="extra-fields"><h3>{tr("Roles & scheduling")}</h3><p className="field-help">{tr("These describe app scheduling, not product safety or medical advice. Changing category resets inferred roles; review them here.")}</p><fieldset className="role-options"><legend>{tr("Functional roles")}</legend>{functionalRoles.map(role => <label key={role}><input type="checkbox" checked={rolesFor(draft).includes(role)} onChange={e => field('roles', e.target.checked ? [...rolesFor(draft), role] : rolesFor(draft).filter(r => r !== role))} />{tr(role.replaceAll('_', ' '))}</label>)}</fieldset>
      <label className="toggle-row"><input type="checkbox" checked={schedulingFor(draft).enabled} onChange={e => field('scheduling', { ...schedulingFor(draft), enabled: e.target.checked })} /> {tr("Include in automatic suggestions")}</label>
      <label>{tr("Step importance")}<select value={schedulingFor(draft).core ? 'core' : 'optional'} onChange={e => field('scheduling', { ...schedulingFor(draft), core: e.target.value === 'core' })}><option value="core">{tr("Core · select within its function group")}</option><option value="optional">{tr("Optional · rotate with recent usage")}</option></select></label>
      <label>{tr("Scheduling intensity")}<select value={schedulingFor(draft).intensity} onChange={e => field('scheduling', { ...schedulingFor(draft), intensity: e.target.value as 'gentle' | 'normal' | 'active' })}><option value="gentle">{tr("Gentle")}</option><option value="normal">{tr("Normal")}</option><option value="active">{tr("Active / intensive")}</option></select></label>
      <div className="form-grid"><label>{tr("Minimum days apart")}<input type="number" min={0} max={365} step={1} value={schedulingFor(draft).minSpacingDays} onChange={e => field('scheduling', { ...schedulingFor(draft), minSpacingDays: Number(e.target.value) })} /></label><label>{tr("Maximum uses / 7 days")}<input type="number" min={1} max={14} step={1} placeholder={tr("No limit")} value={schedulingFor(draft).maxUsesPerWeek ?? ''} onChange={e => field('scheduling', { ...schedulingFor(draft), maxUsesPerWeek: e.target.value ? Number(e.target.value) : null })} /></label></div><p className="field-help">{tr("Spacing uses elapsed 24-hour days. Limits count completed uses over the preceding seven days; they are not usage recommendations.")}</p>
      <label>{tr("Application area")}<input value={draft.applicationArea ?? ''} onChange={e => field('applicationArea', e.target.value)} placeholder={tr("Optional")} /></label>
      {rolesFor(draft).includes('first_cleanse') && <label>{tr("Double-cleanse partner")}<select value={draft.pairWithId ?? ''} onChange={e => field('pairWithId', e.target.value || undefined)}><option value="">{tr("No linked partner")}</option>{products.filter(p => p.id !== draft.id && rolesFor(p).some(r => r === 'second_cleanse' || r === 'gentle_cleanse')).map(p => <option key={p.id} value={p.id}>{p.brand} {p.name}</option>)}{draft.pairWithId && !products.some(p => p.id === draft.pairWithId) && <option value={draft.pairWithId}>{tr("Removed partner · choose another")}</option>}</select></label>}
      </section>
      <section className="extra-fields"><h3>{tr("Advanced ordering")}</h3><label className="toggle-row"><input type="checkbox" checked={draft.autoOrder === false || draft.autoOrder === undefined && !draft.roles} onChange={e => field('autoOrder', !e.target.checked)} /> {tr("Use a custom order number")}</label>{(draft.autoOrder === false || draft.autoOrder === undefined && !draft.roles) && <label>{tr("Custom order")}<input type="number" min={0} max={999} step={1} value={draft.routineOrder} onChange={e => field('routineOrder', Number(e.target.value))} /></label>}<p className="field-help">{tr("Linked oil and foam stay together even with a custom order.")}</p></section>
      <label>{tr("Short instruction")}<input maxLength={240} value={draft.instruction} onChange={e => field('instruction', e.target.value)} placeholder={tr("e.g. 2–3 drops on damp skin")} /></label>
      <label>{tr("Status")}<select value={draft.status} onChange={e => field('status', e.target.value as Product['status'])}><option value="active">{tr("Active — include in routines")}</option><option value="paused">{tr("Paused — taking a break")}</option><option value="finished">{tr("Finished — keep in cabinet")}</option></select></label>
      <section className="extra-fields"><h3>{tr("Dates & notes ")}<span>{tr("Optional")}</span></h3><div className="form-grid"><label>{tr("Date opened")}<input type="date" max={localDate()} value={draft.openedDate} onChange={e => field('openedDate', e.target.value)} /></label><label>{tr("PAO (months)")}<input type="number" min={1} max={120} step={1} value={draft.paoMonths ?? ''} onChange={e => field('paoMonths', e.target.value ? Number(e.target.value) : null)} placeholder={tr("e.g. 12")} /></label></div><label>{tr("Printed expiration date")}<input type="date" value={draft.expirationDate} onChange={e => field('expirationDate', e.target.value)} /></label><label>{tr("Notes")}<textarea rows={3} maxLength={4000} value={draft.notes} onChange={e => field('notes', e.target.value)} /></label><p className="field-help">{tr("The earlier of opening date + PAO and printed expiration is shown. Alerts start 30 days before that date; this does not assess product condition.")}</p></section>
      {lifecycle(draft, undefined, locale) && <p className="default-note">{lifecycle(draft, undefined, locale)!.message}{lifecycle(draft, undefined, locale)!.paoDate && <> {tr("· Opening date + ")}{draft.paoMonths} {tr("months: ")}{dateLabel(lifecycle(draft, undefined, locale)!.paoDate!,locale)}</>}{lifecycle(draft, undefined, locale)!.printedDate && <> {tr("· Printed date: ")}{dateLabel(lifecycle(draft, undefined, locale)!.printedDate!,locale)}</>}</p>}
      {existing && <div className="delete-area">{confirmDelete ? <><p>{tr("Delete this product? Past and started routines will keep their records.")}</p><div className="delete-confirm"><button type="button" className="danger-button" disabled={busy} onClick={() => void onDelete()}>{tr("Delete product")}</button><button type="button" className="text-button" onClick={() => setConfirmDelete(false)}>{tr("Keep product")}</button></div></> : <button type="button" className="text-button danger" onClick={() => setConfirmDelete(true)}><Trash2 size={15} /> {tr("Delete product")}</button>}</div>}
    </div><div className="editor-footer"><button type="button" className="text-button" onClick={onClose} disabled={busy}><ArrowLeft size={16} /> {tr("Cancel")}</button><button type="submit" className="primary" disabled={busy}>{busy ? tr("Saving…") : tr("Save product")}<Check size={17} /></button></div>
  </form></dialog>;
}
