import { rolesFor, type Product } from './model';

export type ProductGuide = { key: string; reviewedOn?: string; brand: string; names: string[]; benefit: string; ingredients: string; use: string; note: string; url: string; source: string; match: 'named' | 'variant-needed' };
export const reviewedOn = 'September 10, 2026';
export const sources = {
 basics: 'https://www.aad.org/public/everyday-care/skin-care-basics/care/apply-skin-care-certain-order',
 moisture: 'https://www.aad.org/public/diseases/acne/skin-care/moisturizer',
 sun: 'https://www.aad.org/public/everyday-care/skin-care-basics/dry/pick-moisturizer',
 exfoliation: 'https://www.aad.org/public/everyday-care/skin-care-basics/care/skin-care-in-your-20s',
};
const skin = 'https://www.skin1004.com/products/';
export const productGuides: ProductGuide[] = [
 {"key": "mist", "reviewedOn":"September 11, 2026", "brand": "SKIN1004", "names": ["Madagascar Centella Hyalu-Cica Cloudy Mist", "Hyalu-Cica Cloudy Mist"], "benefit": "Adds a light layer of hydration and soothing care. This mist is a leave-on step, not a cleanser or a replacement for moisturizer and sunscreen.", "ingredients": "The brand lists green tea water, centella, hyaluronic acid, xylitol and ceramide NP. Check your bottle for the current formula.", "use": "Hold the bottle 20–30 cm from your face and spray once or twice, then let it absorb. Use before creams and sunscreen. If you cleanse, use the mist afterward.", "note": "Reviewed September 11, 2026. Water-only morning washing may suit dry or sensitive skin; this does not make mist a cleansing substitute. Choose your morning start in Settings.", "url": "https://www.skin1004.com/products/skin1004-madagascar-centella-hyalu-cica-cloudy-mist", "source": "SKIN1004 · Hyalu-Cica Cloudy Mist", "match": "named"},
 {key:'centella',brand:'SKIN1004',names:['Madagascar Centella Ampoule','Centella Ampoule'],benefit:'Adds lightweight hydration and soothing care. This is the comfort-focused ampoule, rather than your exfoliating or brightening step.',ingredients:'Centella asiatica extract; the current listed formula also includes glycerin.',use:'Spread a suitable amount evenly, then gently pat it in. In this app: after cleansing or pads, before cream.',note:'Manufacturer describes soothing and hydration benefits. Check your packaging if the formulation differs.',url:skin+'skin1004-madagascar-centella-ampoule',source:'SKIN1004 · Centella Ampoule',match:'named'},
 {key:'hyalu',brand:'SKIN1004',names:['Hyalu-Cica Water-Fit Sun Serum'],benefit:'Provides UV protection with a light, moisturizing finish. It fills the sunscreen step even though its name says serum.',ingredients:'The international formula lists UV filters, centella and hyaluronic acid. The US “UV” version has different filters.',use:'Apply evenly as the last morning skincare step. Follow your tube’s amount, reapplication and water-resistance directions.',note:'International page lists SPF50+ PA++++. Confirm the label and market on your own tube; do not assume water resistance.',url:skin+'hyalu-cica-water-fit-sun-serum-spf50-pa?country=BE&variant=45493174337782',source:'SKIN1004 · international Sun Serum',match:'named'},
 {key:'airfit',brand:'SKIN1004',names:['Centella Air-Fit Suncream Light','Madagascar Centella Air-Fit Suncream Light'],benefit:'Fills the morning UV-protection step. Choose it instead of another sunscreen, not as an extra layer of a second formula.',ingredients:'The official range identifies Light as a mineral sunscreen. Its full current product page could not be verified.',use:'Use as your final morning skincare step and follow your tube’s directions for quantity and reapplication.',note:'Light and Plus are different products. Verify the SPF, UVA rating, ingredients and water resistance on your Light tube before relying on those details.',url:skin+'hyalu-cica-water-fit-sun-serum-spf50-pa?country=BE&variant=45493174337782',source:'SKIN1004 · related Light listing; full directions unverified',match:'variant-needed'},
 {key:'eye',brand:'SKIN1004',names:['Probio-Cica Bakuchiol Eye Cream'],benefit:'Moisturizes the eye area. The brand describes a smoother appearance of fine lines and soothing care.',ingredients:'Bakuchiol, centella, squalane and ceramide NP appear in the manufacturer’s list.',use:'Gently massage a suitable amount around the area of concern from the inside outward, avoiding contact with the eyes. This app places it before moisturizer.',note:'Evening is your editable preference. An eye cream is optional; it is not a substitute for an acne treatment.',url:skin+'probio-cica-bakuchiol-eye-cream',source:'SKIN1004 · eye cream',match:'named'},
 {key:'niacinamide',brand:'SKIN1004',names:['Niacinamide 10 Boosting Shot Ampoule'],benefit:'Targets the appearance of uneven tone, dullness and visible pores. This is a concentrated brightening step with spicules, not a basic hydrating serum.',ingredients:'10% niacinamide, tranexamic acid, ascorbyl glucoside, panthenol and hydrolyzed sponge (spicules).',use:'Manufacturer: introduce 2–3 times weekly for the first 1–2 weeks, using a small amount on the area of concern. Follow with moisturizer. Your app schedules it in the evening and never increases frequency automatically.',note:'Patch test first; avoid irritated or damaged skin and eyes/lips. If irritation persists, stop and seek professional advice. The app’s spacing and intensity limits are editable scheduling defaults.',url:skin+'niacinamide-10-boosting-shot-ampoule',source:'SKIN1004 · Niacinamide 10',match:'named'},
 {key:'mask',brand:'SKIN1004',names:['Poremizing Quick Clay Stick Mask'],benefit:'Clay helps absorb excess surface oil and leaves skin feeling cleaner. It is a rinse-off pore-care option, not a daily essential.',ingredients:'Kaolin and other clays, with centella extract.',use:'After cleansing, apply away from the eyes and mouth. Rinse thoroughly with lukewarm water after 3–5 minutes, then continue with leave-on skincare.',note:'Once weekly is an app default, not a manufacturer requirement. Skip if it leaves your skin tight or uncomfortable.',url:skin+'poremizing-quick-clay-stick-mask',source:'SKIN1004 · clay stick mask',match:'named'},
 {key:'brightpad',brand:'SKIN1004',names:['Tone Brightening Dark Spot Ampoule Pad'],benefit:'Targets the appearance of dark spots and uneven tone, while adding hydration. It overlaps with the niacinamide ampoule’s brightening purpose.',ingredients:'The brand lists 5% niacinamide, a vitamin C complex, kojic acid and other brightening ingredients.',use:'After cleansing, gently sweep with the gauze side, avoiding the eyes. Alternatively, the brand describes placing the jelly side on target areas for 3–5 minutes, then patting in the essence.',note:'This is an active brightening pad, not simply a neutral toner. There is no need to add it to every brightening-serum evening.',url:skin+'tone-brightening-dark-spot-ampoule-pad',source:'SKIN1004 · Dark Spot Pad',match:'named'},
 {key:'porepad',brand:'Medicube',names:['Zero Pore Pad','Zero Pore Pads','Zero Pore Pad 2.0'],benefit:'An exfoliating pad intended to smooth rough texture and reduce the appearance of oily, enlarged-looking pores.',ingredients:'The standard 2.0 page lists lactic acid and salicylic acid. The Mild version is different; confirm which one you own.',use:'For the standard pad: after cleansing, gently sweep with the textured side, then the smooth side, and pat in the remaining liquid.',note:'Evening and limited frequency are conservative app defaults. Confirm standard 2.0 versus Mild before applying ingredient-specific guidance.',url:'https://medicube.us/products/zero-pore-pad-1',source:'Medicube · standard Zero Pore Pad',match:'variant-needed'},
 {key:'vitac',reviewedOn:'September 11, 2026',brand:'Medicube',names:['Deep Vita C Capsule Cream'],benefit:'Moisturizes while targeting dullness and uneven-looking tone. It already adds brightening care, even on evenings without a separate brightening serum.',ingredients:'The brand lists vitamin C, niacinamide, sea buckthorn extract and vitamin E. This is not a plain moisturizer.',use:'Medicube specifies morning and evening use after serum; its guidance does not favor nighttime. Mix the capsule and gel, apply to face and neck, and finish with sunscreen in the morning. Evening-only use can be your preference.',note:'If you want an evening without extra brightening actives, consider a plain moisturizer you tolerate. This is a routine option, not a claim that this cream is incompatible with your treatments.',url:'https://medicube.us/products/deep-vita-c-capsule-cream',source:'Medicube · Deep Vita C',match:'named'},
 {key:'boj',brand:'Beauty of Joseon',names:['Sunscreen','Beauty of Joseon sunscreen','Relief Sun: Rice + Probiotics','Relief Sun'],benefit:'A moisturizing sunscreen that supplies your morning UV-protection step. Choose it instead of the SKIN1004 sunscreen, not alongside it.',ingredients:'Rice extract, fermented ingredients and UV filters in the original Rice + Probiotics formula. This is different from Aqua-Fresh.',use:'Follow the exact bottle’s sunscreen directions. Keep it as the last morning skincare step.',note:'Original Rice + Probiotics version, labeled SPF50+ PA++++. Confirm the market and tube; reapply according to its label.',url:'https://www.yesstyle.com/en/beauty-of-joseon-relief-sun-50ml/info.html/pid.1107744417',source:'YesStyle · Relief Sun Rice + Probiotics listing',match:'named'},
 {key:'roundlab',brand:'Round Lab',names:['1025 Dokdo Cleanser','Dokdo Cleanser'],benefit:'Cleanses surface oil and residue with a soft foam, while supporting a comfortable, hydrated feel. This is a water-based cleanser, not a dedicated exfoliating treatment.',ingredients:'The brand lists deep sea water, panthenol, allantoin and hyaluronic acid. Check your tube for the current ingredient list.',use:'Lather a small amount in wet palms, gently massage over the face and rinse. Your 1–2 times weekly limit is a personal rotation preference, not the manufacturer’s frequency.',note:'Use alone or swap for the linked SKIN1004 oil-and-foam choice.',url:'https://roundlab.com/products/1025-dokdo-cleanser',source:'Round Lab · 1025 Dokdo Cleanser',match:'named'},
 {key:'drg',brand:'Dr.G',names:['R.E.D Blemish Clear Soothing Cream'],benefit:'A lightweight moisturizing option focused on hydration and soothing care. It gives you an alternative to the vitamin C cream.',ingredients:'The brand lists cica ingredients, glycerin, panthenol and niacinamide. This is not a niacinamide-free option.',use:'Spread a suitable amount evenly over the face after lighter skincare and allow it to absorb. Morning or evening; follow with sunscreen in the morning.',note:'Clear Soothing Cream is different from Clear Moisture Cream and Repair Soothing Cream. Compare your jar with the linked page.',url:'https://www.dr-g.com/collections/r-e-d-blemish/products/dr-g-red-blemish-clear-soothing-cream',source:'Dr.G · Clear Soothing Cream',match:'named'},
 {key:'avene',brand:'Avène',names:['Hydrance Light Hydrating Emulsion','Hydrance Light'],benefit:'Light moisturizing care for skin that feels dehydrated or tight. An alternative to your richer or brightening creams.',ingredients:'Avène thermal spring water and moisturizing ingredients. Formulas vary by market; compare your tube. Hydrance Light is not necessarily fragrance-free.',use:'Apply to face and neck morning or evening after cleansing and lighter skincare. The non-SPF version does not replace sunscreen.',note:'Configured as the non-SPF Hydrance Light emulsion; the newer French Light Cream and UV/BB versions can differ.',url:'https://www.eau-thermale-avene.fr/p/hydrance-light-creme-hydratante-3282770399905-14c39aab',source:'Avène · Hydrance Light range; compare your tube',match:'variant-needed'},
 {key:'oil',brand:'SKIN1004',names:['Cleansing oil','Madagascar Centella Light Cleansing Oil'],benefit:'Your first cleanse is intended to lift makeup, sunscreen and oily residue before the linked foam cleanser.',ingredients:'Botanical oils, centella and cleansing emulsifiers; the formula includes aromatic plant oils.',use:'massage onto dry skin with dry hands, add water to emulsify, then rinse thoroughly.',note:'The linked double cleanse is your routine preference, not a requirement for everyone.',url:skin+'skin1004-madagascar-centella-light-cleansing-oil',source:'SKIN1004 · Light Cleansing Oil',match:'named'},
 {key:'foam',brand:'SKIN1004',names:['Cleansing foam','Madagascar Centella Ampoule Foam'],benefit:'Your water-based cleansing step removes remaining surface residue after oil cleansing.',ingredients:'Cleansing surfactants, glycerin and centella in the brand’s current formula.',use:'lather in wet palms, massage gently over the face and rinse with lukewarm water.',note:'Keep one water-based cleanser per routine.',url:skin+'skin1004-madagascar-centella-ampoule-foam',source:'SKIN1004 · Ampoule Foam',match:'named'},
 {key:'differin',brand:'',names:['Differin'],benefit:'An adapalene retinoid medicine for acne. It is a treatment step, not an extra cosmetic brightening serum.',ingredients:'Adapalene. Your strength and gel/cream formulation are not recorded; the linked US label is for 0.1% gel.',use:'Follow your own label or clinician’s directions for amount, area and frequency. Automatic scheduling stays off until you configure it.',note:'Can cause dryness and irritation. Avoid damaged skin and protect from sun. Ask a clinician before use during pregnancy or breastfeeding. Review combinations with your pharmacist rather than increasing treatments automatically.',url:'https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=0739d631-171b-42a8-bd55-0022b8df2d8a',source:'DailyMed · Differin 0.1% gel label, confirm strength',match:'variant-needed'},
 {key:'cutacnyl',brand:'',names:['Cutacnyl'],benefit:'A benzoyl peroxide medicine for acne. Your application area is the chin; this does not establish the dose or frequency.',ingredients:'Benzoyl peroxide; strength unconfirmed. The linked French leaflet is for 2.5%.',use:'Follow your tube’s leaflet or clinician’s directions. The app keeps automatic suggestions off until you set your treatment schedule.',note:'May irritate skin and bleach fabrics. Keep away from eyes and mucous membranes. Confirm the strength and discuss other exfoliating or acne treatments with your pharmacist.',url:'https://base-donnees-publique.medicaments.gouv.fr/medicament/60809088/extrait',source:'French medicines database · Cutacnyl 2.5% leaflet',match:'variant-needed'},
];
const normalize = (s: string) => s.trim().toLowerCase().replace(/\s+/g, ' ');
// Match names and brands, never a seed ID alone: a user may repurpose a starter row.
export function guideFor(p: Pick<Product, 'name' | 'brand'>): ProductGuide | undefined {
 return productGuides.find(g => (normalize(g.brand) === normalize(p.brand) || !g.brand && ['', 'galderma'].includes(normalize(p.brand))) && g.names.some(n => normalize(n) === normalize(p.name) || normalize('Madagascar Centella '+n) === normalize(p.name)));
}
export function benefitFor(p: Product): string {
 const guide = guideFor(p); if (guide) return guide.benefit;
 const roles = rolesFor(p);
 if (roles.includes('sunscreen')) return 'Your configured sun-protection step. Check your label for SPF, UVA protection and directions.';
 if (roles.includes('moisturizer')) return 'Your configured moisturizing step, intended to reduce dryness and retain moisture.';
 if (roles.some(r => ['first_cleanse','second_cleanse','gentle_cleanse'].includes(r))) return 'Your configured cleansing step, intended to remove surface residue.';
 if (roles.includes('brightening')) return 'Assigned to your tone-evening step. Benefits and ingredients have not been verified for this product.';
 if (roles.some(r => ['hydrating','soothing'].includes(r))) return 'Assigned to hydration and comfort. Product-specific benefits have not been verified.';
 return 'Included for the role you assigned. Add the exact product name to distinguish its purpose; product-specific benefits are not verified.';
}
